add_noise: null
amp: true
augs_mix:
- mixup
- timemix
- freqmix
- phmix
augs_noise:
- awgn
- abgn
- apgn
- argn
- avgn
- aun
- phn
- sine
augs_signal:
- amp
- neg
- tshift
- tmask
- ampsegment
- cycshift
batch_size: 128
data_path: ../data/finger
data_subtype: balanced
dataset: finger
dim_feedforward: 512
ds_factors:
- 4
- 4
- 4
ema: 0.995
emb_dim: 128
epoch_mix: 12
ext_pretrained: null
f_res: !!python/object/apply:pathlib.PosixPath
- models
- avocados
filter_bias_and_bn: true
fold_id: null
gpu_ids:
- 0
kd_model: null
load_path: null
local_rank: 0
log_interval: 100
loss_type: label_smooth
max_lr: 0.0003
mix_loss: bce
mix_ratio: 1.0
model_type: SoundNetRaw
multilabel: false
n_classes: 10
n_epochs: 350
n_head: 8
n_layers: 4
nf: 16
num_workers: 2
resume_training: false
run_name: !!python/object/apply:pathlib.PosixPath
- 500_9_0.2_r1
sampling_rate: 22050
save_interval: 100
save_path: !!python/object/apply:pathlib.PosixPath
- /
- content
- drive
- MyDrive
- model
- finger
scheduler: null
seq_len: 16384
use_balanced_sampler: false
use_bg: false
use_ddp: false
use_dp: false
wd: 1.0e-05
